apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: rhdh-rc-17-java-springboot-github-oogyxhjb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhdh-rc-17-java-springboot-github-oogyxhjb 
  name: rhdh-rc-17-java-springboot-github-oogyxhjb
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: rhdh-rc-17-java-springboot-github-oogyxhjb
    weight: 100 
