apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rhdh-rc-17-java-springboot-github-oogyxhjb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhdh-rc-17-java-springboot-github-oogyxhjb 
  name: rhdh-rc-17-java-springboot-github-oogyxhjb
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rhdh-rc-17-java-springboot-github-oogyxhjb 
